# Generated by Django 4.2.5 on 2023-09-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SymbolTokenMappingSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=20, unique=True)),
                ("symbol", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("expiry", models.DateField(blank=True, null=True)),
                ("strike", models.DecimalField(decimal_places=6, max_digits=10)),
                ("lotsize", models.IntegerField()),
                (
                    "instrumenttype",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("exch_seg", models.CharField(max_length=20)),
                ("tick_size", models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
    ]
