# Generated by Django 4.2.5 on 2023-09-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("angel_broking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="symboltokenmappingsheet",
            name="strike",
            field=models.CharField(max_length=50),
        ),
    ]
