# Generated by Django 4.2.5 on 2023-09-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("angel_broking", "0003_alter_symboltokenmappingsheet_tick_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="symboltokenmappingsheet",
            name="token",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
