# Generated by Django 4.2.5 on 2023-09-06 04:12

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('univest_id', models.IntegerField(unique=True)),
                ('streamChannelId', models.CharField(blank=True, max_length=255, null=True)),
                ('streamMessageId', models.CharField(blank=True, max_length=255, null=True)),
                ('senderId', models.IntegerField()),
                ('stockName', models.CharField(max_length=255)),
                ('suggestedPrice', models.FloatField()),
                ('expiresAt', models.BigIntegerField()),
                ('targetPrice', models.FloatField()),
                ('stopLoss', models.FloatField(blank=True, null=True)),
                ('recommendationType', models.CharField(max_length=50)),
                ('confidenceLevel', models.CharField(blank=True, max_length=50, null=True)),
                ('closureReason', models.CharField(blank=True, max_length=255, null=True)),
                ('bsePriceAtClosure', models.FloatField(blank=True, null=True)),
                ('nsePriceAtClosure', models.FloatField(blank=True, null=True)),
                ('createdAt', models.BigIntegerField()),
                ('lastModified', models.BigIntegerField()),
                ('channelName', models.CharField(blank=True, max_length=255, null=True)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(blank=True, max_length=255, null=True)),
                ('senderContactNumber', models.CharField(max_length=20)),
                ('profilePictureUrl', models.URLField(blank=True, null=True)),
                ('open', models.BooleanField()),
                ('hit', models.BooleanField()),
                ('finCode', models.IntegerField()),
                ('expectedDurationEnum', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('watchListIds', jsonfield.fields.JSONField(blank=True, null=True)),
                ('analysis', models.TextField(blank=True, null=True)),
                ('attachments', jsonfield.fields.JSONField(blank=True, null=True)),
                ('term', models.CharField(max_length=50)),
                ('newTradeCard', models.BooleanField()),
                ('locked', models.BooleanField()),
                ('logoUrl', models.URLField(blank=True, null=True)),
                ('compName', models.CharField(blank=True, max_length=255, null=True)),
                ('netGain', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data', jsonfield.fields.JSONField()),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='univest.idea')),
            ],
        ),
    ]
