# Generated by Django 4.2.5 on 2023-09-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univest', '0002_history_created_at_history_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='expectedDurationEnum',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
