# Generated by Django 4.2.5 on 2023-09-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univest', '0003_alter_idea_expecteddurationenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='idea',
            name='attachments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='watchListIds',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
