# Generated by Django 4.2.5 on 2023-09-06 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('univest', '0004_alter_history_data_alter_idea_attachments_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
