# Generated by Django 4.2.5 on 2023-09-06 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('univest', '0006_historicalidea'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalIdea',
        ),
    ]
