# Generated by Django 4.2.5 on 2023-09-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("univest", "0012_remove_ideastatus_order_order_idea_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="amount",
            field=models.FloatField(null=True, verbose_name="Amount"),
        ),
    ]
